#pragma kernel QuadraticCurve3D

RWTexture3D<float> _Output;

float _Radius;

float3 _MinBounds;
float3 _MaxBounds;

[numthreads(8,8,8)]
void QuadraticCurve3D (uint3 id : SV_DispatchThreadID)
{
    uint width, height, depth;
    _Output.GetDimensions(width, height, depth);
    if(id.x >= width || id.y >= height || id.z >= depth) return;
    float3 uvw = 
        (float3(id.x, id.y, id.z) + 0.5f) 
        / float3(width, height, depth);
    float3 pos = lerp(_MinBounds, _MaxBounds, uvw);
    
    float x = length(pos.xyz);
    
    _Output[id] = x - _Radius;
}
