#pragma kernel MarchingCubes

#include "MarchingTable.hlsl"

struct Triangle {
    float3 a, b, c;
};

Texture3D<float> _Input;
SamplerState sampler_Input;

AppendStructuredBuffer<Triangle> _Triangles;

uint _Resolution;
float _Threshold;

float3 _Min;
float3 _Max;

float3 interp(
    float3 edgeVertex1, float valueAtVertex1, 
    float3 edgeVertex2, float valueAtVertex2)
{
    return (
        edgeVertex1 + 
        (_Threshold - valueAtVertex1) * (edgeVertex2 - edgeVertex1) 
        / (valueAtVertex2 - valueAtVertex1));
}

float3 remap(
    float3 value, float3 fromMin, float3 fromMax,
    float3 toMin, float3 toMax)
{
    return (value - fromMin) / (fromMax - fromMin) * (toMax - toMin) + toMin;
}

[numthreads(8,8,8)]
void MarchingCubes (uint3 id : SV_DispatchThreadID)
{
    if(
        id.x >= _Resolution || 
        id.y >= _Resolution || 
        id.z >= _Resolution) return;

    float3 pos = float3(id) / float(_Resolution);

    int i;
    float cubeValues[8];
    for (i = 0; i < 8; i++)
    {
        float3 offset = cornerOffsets[i] * (1.0 / float(_Resolution));
        cubeValues[i] = _Input.SampleLevel(sampler_Input, pos + offset, 0).r;
    }

    int cubeIndex = 0;
    if (cubeValues[0] < _Threshold) cubeIndex |= 1;
    if (cubeValues[1] < _Threshold) cubeIndex |= 2;
    if (cubeValues[2] < _Threshold) cubeIndex |= 4;
    if (cubeValues[3] < _Threshold) cubeIndex |= 8;
    if (cubeValues[4] < _Threshold) cubeIndex |= 16;
    if (cubeValues[5] < _Threshold) cubeIndex |= 32;
    if (cubeValues[6] < _Threshold) cubeIndex |= 64;
    if (cubeValues[7] < _Threshold) cubeIndex |= 128;

    int edges[] = triTable[cubeIndex];

    for (i = 0; edges[i] != -1; i += 3)
    {
        // First edge lies between vertex e00 and vertex e01
        int e00 = edgeConnections[edges[i]][0];
        int e01 = edgeConnections[edges[i]][1];
        // Second edge lies between vertex e10 and vertex e11
        int e10 = edgeConnections[edges[i + 1]][0];
        int e11 = edgeConnections[edges[i + 1]][1];
        // Third edge lies between vertex e20 and vertex e21
        int e20 = edgeConnections[edges[i + 2]][0];
        int e21 = edgeConnections[edges[i + 2]][1];

        Triangle tri;
        tri.a = (interp(
            cornerOffsets[e00], cubeValues[e00], 
            cornerOffsets[e01], cubeValues[e01]) + id) 
            / float(_Resolution);
        tri.b = (interp(
            cornerOffsets[e10], cubeValues[e10], 
            cornerOffsets[e11], cubeValues[e11]) + id) 
            / float(_Resolution);
        tri.c = (interp(
            cornerOffsets[e20], cubeValues[e20], 
            cornerOffsets[e21], cubeValues[e21]) + id) 
            / float(_Resolution);

        // Remap the triangle vertices from [0, 1] to [-0.5, 0.5]
        tri.a = remap(tri.a, 
            float3( 0, 0, 0), float3(1, 1, 1), 
            _Min, _Max);
        
        tri.b = remap(tri.b,
            float3( 0, 0, 0), float3(1, 1, 1), 
            _Min, _Max);
        
        tri.c = remap(tri.c,
            float3( 0, 0, 0), float3(1, 1, 1), 
            _Min, _Max);

        _Triangles.Append(tri);
    }
}
