#pragma kernel Clear
#pragma kernel FetchSubgrids
#pragma kernel FetchStarts
#pragma kernel SortSubgrids

const float PI = 3.14159265358979323846f;

RWStructuredBuffer<float3> Positions;
RWStructuredBuffer<uint> ParticlesIndices;
RWStructuredBuffer<uint> SubgridIndices;
RWStructuredBuffer<uint> SubgridStarts;
RWStructuredBuffer<uint> SubgridCounts;

/* example
    ParticlesIndices: [3, 1, 0, 2, 13, 8, 9, 7, 5, 4, 6, 12, 10, 11, 14, 15]
    SubgridIndices:   [0, 0, 1, 1,  1, 1, 2, 3, 3, 4, 4,  4,  4,  5,  5,  7]
    SubgridStarts:    [0, 2, 6, 7, 9, 13, 15, 15]

    for (int i = SubgridStarts[idx]; i < SubgridStarts[idx + 1]; i++) ...
*/

uint PartitionResolution;

float3 CenterBound;
float3 SizeBound;

uint GetSubgridIndex(float3 position) {
    float3 subgridSize = SizeBound / (PartitionResolution - 1);
    float3 positionInBound = position - CenterBound + SizeBound / 2.0f;
    uint3 subgridIndex = (uint3)(positionInBound / subgridSize);
    return 
          subgridIndex.x 
        + subgridIndex.y * PartitionResolution 
        + subgridIndex.z * PartitionResolution * PartitionResolution;
}

[numthreads(256, 1, 1)]
void Clear(uint3 id : SV_DispatchThreadID) {
    uint SubgridCount, SubgridStride;
    SubgridCounts.GetDimensions(SubgridCount, SubgridStride);
    if (id.x >= SubgridCount)
        return;
    SubgridCounts[id.x] = 0;
}

[numthreads(256, 1, 1)]
void FetchSubgrids(uint3 id : SV_DispatchThreadID) {
    uint ParticleCount, ParticleStride;
    Positions.GetDimensions(ParticleCount, ParticleStride);
    if (id.x >= ParticleCount) 
        return;

    float3 position = Positions[id.x];
    uint subgridIndex = GetSubgridIndex(position);

    // Store the particle index in the subgrid
    ParticlesIndices[id.x] = id.x;
    SubgridIndices[id.x] = subgridIndex;

    InterlockedAdd(SubgridCounts[subgridIndex], 1);
}

[numthreads(256, 1, 1)]
void FetchStarts(uint3 id : SV_DispatchThreadID) {
    uint SubgridCount, SubgridStride;
    SubgridCounts.GetDimensions(SubgridCount, SubgridStride);
    if (id.x >= SubgridCount)
        return;

    // Store the starting index of each subgrid
    uint count = SubgridCounts[id.x];
    for (uint i = 0; i < id.x; i++) {
        count += SubgridCounts[i];
    }
    SubgridStarts[id.x] = count;
}

void Swap(uint a, uint b) {
    if (a == b) return;
    uint tempIndex = ParticlesIndices[a];
    ParticlesIndices[a] = ParticlesIndices[b];
    ParticlesIndices[b] = tempIndex;

    uint tempSubgrid = SubgridIndices[a];
    SubgridIndices[a] = SubgridIndices[b];
    SubgridIndices[b] = tempSubgrid;
}

void CompareAndSwapPerSubgrid(uint a, uint b) {
    if (a == b) return;
    if (SubgridIndices[a] < SubgridIndices[b]) {
        Swap(a, b);
    } else if (SubgridIndices[a] > SubgridIndices[b]) {
        return;
    } else  // SubgridIndices[a] == SubgridIndices[b]
    {
        if (ParticlesIndices[a] > ParticlesIndices[b]) {
            Swap(a, b);
        }
    }
}

[numthreads(256, 1, 1)]
void SortSubgrids(uint3 id : SV_DispatchThreadID) {
    // Bitonic parallel sort on ParticlesIndices and SubgridIndices together
    uint ParticleCount, ParticleStride;
    ParticlesIndices.GetDimensions(ParticleCount, ParticleStride);
    if (id.x >= ParticleCount) 
        return;

    float powerf = log2((float)ParticleCount);
    uint power = (uint)ceil(powerf);
    // Power of 2 ceiling for the particle count
    uint powerOf2Size = 1u << power;

    // Loop through each stage of the bitonic sort
    for (uint k = 2; k <= powerOf2Size; k <<= 1) {
        GroupMemoryBarrierWithGroupSync();
        
        for (uint j = k/2; j > 0; j >>= 1) {
            GroupMemoryBarrierWithGroupSync();
            uint ij = id.x ^ j;
            
            if (ij > id.x && ij < ParticleCount) {
                CompareAndSwapPerSubgrid(id.x, ij);
            }
            
            GroupMemoryBarrierWithGroupSync();
        }
    }
}
